# Use a lightweight JDK image
FROM eclipse-temurin:23-jdk

# Set the working directory inside the container
WORKDIR /api-gateway

# Copy the JAR file (adjust based on your build tool)
COPY target/*.jar api-gateway.jar

# Expose the application's port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "api-gateway.jar"]