version: '3.8'

services:
  service-registry:
    image: service-registry:latest
    build:
      context: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=local  # Set local profile

  api-gateway:
    image: api-gateway:latest  # Name of the image
    build:
      context: ./api-gateway  # Directory containing Dockerfile for api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"  # Map container port to localhost
    depends_on:
      - service-registry
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/  # Ensures Eureka uses container name

  product-service:
    image: product-service:latest
    build:
      context: ./product-service  # Directory containing Dockerfile for product-service
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/  # Ensures Eureka uses container name

  order-service:
    image: order-service:latest
    build:
      context: ./order-service  # Directory containing Dockerfile for order-service
    ports:
      - "8081:8081"
    depends_on:
      - product-service
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/  # Ensures Eureka uses container name

networks:
  app-network:
    driver: bridge