global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8082']

#  - job_name: 'otel-collector'
#    static_configs:
#      - targets: ['otel-collector:9464']