spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service  # Load-balanced Eureka service name
          predicates:
            - Path=/api/products/**
          filters:
            - RewritePath=/api/products/(?<segment>.*), /api/products/${segment}

        - id: order-service
          uri: lb://order-service  # Load-balanced Eureka service name
          predicates:
            - Path=/api/orders/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG