# Use a lightweight JDK image
FROM eclipse-temurin:23-jdk

# Set the working directory inside the container
WORKDIR /config-server

# Copy the JAR file (adjust based on your build tool)
COPY target/*.jar config-server.jar

# Expose the application's port
EXPOSE 8888

# Run the application
ENTRYPOINT ["java", "-jar", "config-server.jar"]