apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      #hostNetwork: true  # <-- This line allows Kubernetes pods to access local network
      containers:
        - name: product-service
          image: product-service:latest  # Uses the local Minikube image
          imagePullPolicy: Never  # <-- This tells Kubernetes NOT to pull from a registry
          #imagePullPolicy: IfNotPresent  # Change this if using an external registry
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"  # Ensure it's using the Kubernetes profile
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  #type: NodePort
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      #nodePort: 30080  # This exposes the service on localhost:30080
  type: ClusterIP  # Internal service (change to NodePort if needed)