# Use a lightweight JDK image
FROM eclipse-temurin:23-jdk

# Set the working directory inside the container
WORKDIR /service-registry

# Copy the JAR file (adjust based on your build tool)
COPY target/*.jar service-registry.jar

# Expose the application's port
EXPOSE 8761

# Run the application
ENTRYPOINT ["java", "-jar", "service-registry.jar"]