apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      #hostNetwork: true  # <-- This line allows Kubernetes pods to access local network
      containers:
        - name: service-registry
          image: service-registry:latest  # Uses the local Minikube image
          imagePullPolicy: Never  # <-- This tells Kubernetes NOT to pull from a registry
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"  # Ensure it's using the Kubernetes profile
            - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
              value: "false"  # Optional: Disables self-preservation for testing
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
spec:
  #type: NodePort
  selector:
    app: service-registry
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      #nodePort: 30080  # This exposes the service on localhost:30080
  clusterIP: None  # Headless service for internal DNS resolution