server:
  port: 8081

#spring:
#  datasource:
#    url: jdbc:postgresql://prod-db-host:5432/microservice_db
#    driver-class-name: org.postgresql.Driver
#    username: prod_user
#    password: prod_password
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: false

logging:
  level:
    root: WARN
    org.csk.micro: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/